# This is a basic workflow to help you get started with Actions

name: Clone Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "clone"
  clone:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: clone repository in the correct location on TerpConnect
        uses: actions/checkout@v3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secret.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: git clone git@github.com:1onQ/cmsc389T-web-template.git
